name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y memcached libmemcached-dev gcc zlib1g-dev
        rm -rf /var/lib/apt/lists/*
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install deps/wsctools
        pip install .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
